### ISSUE TITLE
iOS Keychain Module

### ISSUE THREAD

**Issue by matthewphewes** [obscure-com/ti_keychain#1]
Hi, I seem to be having trouble while building an app with the iOS version of the module... Any help is greatly appreciated.

``` python
[ERROR] clang: error: linker command failed with exit code 1 (use -v to see invocation)
[ERROR] 
[ERROR] Error: Traceback (most recent call last):
  File "/Users/matthew/Library/Application Support/Titanium/mobilesdk/osx/1.8.0.1/iphone/builder.py", line 1274, in main
    execute_xcode("iphonesimulator%s" % link_version,["GCC_PREPROCESSOR_DEFINITIONS=__LOG__ID__=%s DEPLOYTYPE=development TI_DEVELOPMENT=1 DEBUG=1 TI_VERSION=%s %s %s" % (log_id,sdk_version,debugstr,kroll_coverage)],False)
  File "/Users/matthew/Library/Application Support/Titanium/mobilesdk/osx/1.8.0.1/iphone/builder.py", line 1180, in execute_xcode
    output = run.run(args,False,False,o)
  File "/Users/matthew/Library/Application Support/Titanium/mobilesdk/osx/1.8.0.1/iphone/run.py", line 39, in run
    sys.exit(rc)
SystemExit: 65
```

In the Xcode project, it's just a bunch of Mach-O Linker errors...

Thanks!

**Comment by pegli** [comment]
When you see an SystemExit: 65 message, it means that the Python build script failed, usually because of an error when it calls the xcodebuild command.  The script should have written a file named "build.log" in your build directory, usually under build/iphone/build/build.log.  That file captures the output of xcodebuild and should contain the actual error that is preventing the build from running.

If you have trouble figuring out what is going on from the build.log file, please paste the last 20-30 lines into a comment here and I'll take a look.  Thanks!

**Comment by matthewphewes** [comment]
Here's the errors it is outputting. I think it's having trouble linking to the KeychainItemWrapper... Lately, Mach-O Linker errors have been driving me crazy haha... Thanks for your help. I'm still new @ Xcode & Objective-C but I'm slowly learning...

``` python
Ld build/Debug-iphonesimulator/Peak.app/Peak normal i386
    cd /Users/matthew/Apps/Peak/build/iphone
    setenv MACOSX_DEPLOYMENT_TARGET 10.6
    setenv PATH "/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin/clang++ -arch i386 -isysroot /Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator5.0.sdk -L/Users/matthew/Apps/Peak/build/iphone/build/Debug-iphonesimulator -L/Users/matthew/Apps/Peak/build/iphone/lib "-L/Users/matthew/Library/Application Support/Titanium/modules/iphone/com.obscure.keychain/1.0" "-L/Users/matthew/Library/Application Support/Titanium/modules/iphone/tibar/0.4.2" "-L/Users/matthew/Library/Application Support/Titanium/modules/iphone/com.obscure.keychain/1.0" "-L/Users/matthew/Library/Application Support/Titanium/modules/iphone/tibar/0.4.2" -F/Users/matthew/Apps/Peak/build/iphone/build/Debug-iphonesimulator -filelist /Users/matthew/Apps/Peak/build/iphone/build/Peak.build/Debug-iphonesimulator/Peak.build/Objects-normal/i386/Peak.LinkFileList -mmacosx-version-min=10.6 -Xlinker -objc_abi_version -Xlinker 2 -ObjC -framework AVFoundation -framework CoreMedia -framework CoreVideo -framework QuartzCore /usr/lib/libiconv.dylib -framework AVFoundation -framework CoreMedia -framework CoreVideo -framework QuartzCore /usr/lib/libiconv.dylib -weak_framework iAd -weak_framework iAd -Xlinker -no_implicit_dylibs -D__IPHONE_OS_VERSION_MIN_REQUIRED=40000 -licucore -framework Foundation -weak_framework UIKit -framework CoreGraphics -framework AddressBook -framework AddressBookUI -framework CFNetwork -framework CoreLocation -framework MapKit -framework MessageUI -framework MobileCoreServices -framework OpenGLES -framework QuartzCore -framework SystemConfiguration -lsqlite3 -lz -framework AudioToolbox -weak_framework MediaPlayer -framework AVFoundation -lxml2 -framework StoreKit -lTiCore -lcom.obscure.keychain -ltibar -lcom.obscure.keychain -ltibar -framework ExternalAccessory -ltiverify -lti_ios_debugger -o /Users/matthew/Apps/Peak/build/iphone/build/Debug-iphonesimulator/Peak.app/Peak
Undefined symbols for architecture i386:
  "_SecItemCopyMatching", referenced from:
      -[KeychainItemWrapper initWithIdentifier:accessGroup:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapper secItemFormatToDictionary:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapper writeToKeychain] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
  "_SecItemDelete", referenced from:
      -[KeychainItemWrapper resetKeychainItem] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
  "_SecItemUpdate", referenced from:
      -[KeychainItemWrapper writeToKeychain] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
  "_SecItemAdd", referenced from:
      -[KeychainItemWrapper writeToKeychain] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
  "_kSecAttrAccessGroup", referenced from:
      -[KeychainItemWrapper writeToKeychain] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
  "_kSecAttrAccount", referenced from:
      -[KeychainItemWrapper resetKeychainItem] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapperProxy account] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
      -[KeychainItemWrapperProxy setAccount:] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
      -[KeychainItemWrapper resetKeychainItem] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapperProxy account] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
      -[KeychainItemWrapperProxy setAccount:] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
  "_kSecAttrDescription", referenced from:
      -[KeychainItemWrapper resetKeychainItem] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapperProxy description] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
      -[KeychainItemWrapperProxy setDescription:] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
      -[KeychainItemWrapper resetKeychainItem] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapperProxy description] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
      -[KeychainItemWrapperProxy setDescription:] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
  "_kSecAttrGeneric", referenced from:
      -[KeychainItemWrapper initWithIdentifier:accessGroup:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
  "_kSecAttrLabel", referenced from:
      -[KeychainItemWrapper resetKeychainItem] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
  "_kSecClass", referenced from:
      -[KeychainItemWrapper initWithIdentifier:accessGroup:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapper dictionaryToSecItemFormat:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapper secItemFormatToDictionary:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapper writeToKeychain] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
  "_kSecClassGenericPassword", referenced from:
      -[KeychainItemWrapper initWithIdentifier:accessGroup:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapper dictionaryToSecItemFormat:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapper secItemFormatToDictionary:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
  "_kSecMatchLimit", referenced from:
      -[KeychainItemWrapper initWithIdentifier:accessGroup:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
  "_kSecMatchLimitOne", referenced from:
      -[KeychainItemWrapper initWithIdentifier:accessGroup:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
  "_kSecReturnAttributes", referenced from:
      -[KeychainItemWrapper initWithIdentifier:accessGroup:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
  "_kSecReturnData", referenced from:
      -[KeychainItemWrapper secItemFormatToDictionary:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
  "_kSecValueData", referenced from:
      -[KeychainItemWrapper resetKeychainItem] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapper dictionaryToSecItemFormat:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapper secItemFormatToDictionary:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapperProxy valueData] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
      -[KeychainItemWrapperProxy setValueData:] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
      -[KeychainItemWrapper resetKeychainItem] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapper dictionaryToSecItemFormat:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapper secItemFormatToDictionary:] in libcom.obscure.keychain.a(KeychainItemWrapper.o)
      -[KeychainItemWrapperProxy valueData] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
      -[KeychainItemWrapperProxy setValueData:] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
  "_kSecAttrComment", referenced from:
      -[KeychainItemWrapperProxy comment] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
      -[KeychainItemWrapperProxy setComment:] in libcom.obscure.keychain.a(KeychainItemWrapperProxy.o)
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)


** BUILD FAILED **


The following build commands failed:
    Ld build/Debug-iphonesimulator/Peak.app/Peak normal i386
(1 failure)
EXIT CODE WAS: 65

Exception detected in script:
Traceback (most recent call last):
  File "/Users/matthew/Library/Application Support/Titanium/mobilesdk/osx/1.8.0.1/iphone/builder.py", line 1274, in main
    execute_xcode("iphonesimulator%s" % link_version,["GCC_PREPROCESSOR_DEFINITIONS=__LOG__ID__=%s DEPLOYTYPE=development TI_DEVELOPMENT=1 DEBUG=1 TI_VERSION=%s %s %s" % (log_id,sdk_version,debugstr,kroll_coverage)],False)
  File "/Users/matthew/Library/Application Support/Titanium/mobilesdk/osx/1.8.0.1/iphone/builder.py", line 1180, in execute_xcode
    output = run.run(args,False,False,o)
  File "/Users/matthew/Library/Application Support/Titanium/mobilesdk/osx/1.8.0.1/iphone/run.py", line 39, in run
    sys.exit(rc)
SystemExit: 65
```

**Comment by pegli** [comment]
Looks like it isn't linking against Security.framework.  In Xcode, open the project and select "keychain" in the left hand view, then the Target named "keychain".  Under Build Phases, expand "Link Binary With Libraries" and ensure that you see Security.framework and Foundation.framework.  If Security.framework is missing, add it and see if that fixes the issue.

You can also download the prebuilt version if you aren't interested in building it yourself:

https://github.com/pegli/ti_keychain/downloads

**Comment by matthewphewes** [comment]
Thanks so much - worked perfectly!
